title: Dilip C M
logo: /assets/img/DilipProfile.jpeg
description: Experienced ReactJS developer with 1.5 Yrs. of experience in the industry. Seeking to leverage high proficiency in ReactJS and Web Development Technologies in a full-time career.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
